export enum ConfigurationBarOptions {
    TRANSLANDAR = 'TRANSLANDAR',
    ESCALONAR = 'ESCALONAR',
    ROTACIONAR = 'ROTACIONAR',
    AVIOES_PROXIMOS = 'AVIOES_PROXIMOS',
    DISTANCIA_MINIMA = 'DISTANCIA_MINIMA',
    EM_ROTA_COLISAO = 'EM_ROTA_COLISAO',
}
